<?php
  /* $products = Mage::getResourceModel('catalog/product_collection');
   $products->addAttributeToSelect('*');
   $products->addAttributeToFilter('visibility', array('neq' => 1));
   $products->addAttributeToFilter('status', 1);
   $products->addAttributeToFilter('series', 1);
   $products->setCurPage(1)->setPageSize(1);
   $products->setOrder('name','asc');//Added by bijal to show sort order
   $products->load();*/
 //  echo "<pre>";
 //Load product model collecttion filtered by attribute set id
$products = Mage::getModel('catalog/product')->getCollection()
	->addAttributeToSelect(array('entity_id','name','url_path','series_title'))
	->addAttributeToFilter('visibility', array('neq' => 1))
    ->addAttributeToFilter('status', 1)
    ->addAttributeToFilter('series', 1)
    ->setOrder('series_title','asc')
    ->setOrder('name','asc')
    ->addFieldToFilter('series', 1);
    //echo $products->getSelect();
?>
<h3>Shop by Series</h3>
<select name="Pick a Product Family" onchange="window.location=this.value">
	      <option value="Pick a Product Family">Pick a Product Family</option>
<?php 
$baseUrl= Mage::getBaseUrl();
foreach($products as $p){
$name = $p->getData('series_title');
if($name == '')
{
	$name = $p->getData('name');
}
?>
	<option value="<?php echo $baseUrl.$p->getData('url_path') ?>"><?php echo $name; ?></option>
 <?php } ?>
	    </select>
