<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.2.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
    
<?php if ($this->getShowReviews()): ?>
<?php if (Mage::helper('advancedreviews')->checkVersion('1.4.0.0')): ?>
	<div class="box-collateral box-reviews" id="customer-reviews">
		<?php if (count($this->getCollection())):?>
			<h2>
			<span style="float:left;"><?php echo $this->__('Product Reviews') ?> </span>
				<span style="float:right;">
					<a href="<?php echo Mage::getBlockSingleton('review/helper')->getReviewsUrl() ?>" style="color:#444;font-weight:normal;text-decoration:none;" rel="iframe-680-530" title="Write A Review"  class="pirobox_gall1">
					<?php echo $this->__('Write a review for this product') ?></a>
				</span>
			</h2>
			<dl>
			<?php foreach ($this->getCollection() as $_review):?>
				<!--<dt>
					<a href="<?php //echo $this->getReviewUrl($_review->getId()) ?>" rel="iframe-680-250"  class="pirobox_gall1" title="<?php //echo $this->__('Review by %s', $this->htmlEscape($_review->getNickname())) ?>"><?php //echo $this->htmlEscape($_review->getTitle()) ?></a> <?php // echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
					<?php //echo $this->getChild('advancedreviews_allmylink')->setReview($_review)->toHtml()  ?>
				</dt>-->
				<dd>
				<?php $_votes = $_review->getRatingVotes(); ?>
					<?php if (count($_votes)): ?>
					<table class="ratings-table">
						<col width="1" />
						<col />
						<tbody>
							<?php foreach ($_votes as $_vote): ?>
							<tr>
								<th style="width:86px;"><?php echo $_vote->getRatingCode() ?></th>
								<td>
									<div class="rating-box">
										<div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
									</div>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php endif; ?>
					<?php
						echo $this->getChild('advancedreviews_proscons_indicator')->setReviewId( $_review->getId() )->toHtml();
						echo $this->getChild('advancedreviews_recommend_indicator')->setReviewId( $_review->getId() )->toHtml();
						echo $this->getChild('advancedreviews_footer')->setReviewId( $_review->getId() )->toHtml();
					?>
					<?php echo '"'. nl2br($this->htmlEscape($_review->getDetail())) ;?><b><i><?php echo '" - '. $this->htmlEscape(ucwords($_review->getNickname())) .($this->htmlEscape($_review->getLocation())?', '.$this->htmlEscape($_review->getLocation()):'')?></i></b><!--<small class="date"><?php //echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt(), 'short')) ?></small> -->
					
				
					
					
				</dd>
			<?php endforeach; ?>
			</dl>
		<?php endif;?>
	</div>
<?php else: ?>
	<h2><?php echo $this->__('Product Reviews')?></h2>
    <?php if (count($this->getCollection())):?>
	<div class="collateral-box dedicated-review-box" id="customer-reviews">

		<h2><?php echo $this->__('Product Reviews') ?> 
			<span style="float:right;">
				<a href="<?php echo Mage::getBlockSingleton('review/helper')->getReviewsUrl() ?>" style="color:#444;font-weight:normal;text-decoration:none;"  rel="iframe-680-530"  title="Write A Review" class="pirobox_gall1" ><?php echo $this->__('Write a review for this product') ?></a>
			</span>
		</h2>
		<ol style="margin-top:15px;">
			<?php foreach ($this->getCollection() as $_review):?>
				<li>
					<a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><strong><?php echo $this->htmlEscape($_review->getTitle()) ?></strong></a> <?php echo $this->__('Review by %s', $this->htmlEscape($_review->getNickname())) ?>
					<?php echo $this->getChild('advancedreviews_allmylink')->setReview($_review)->toHtml()  ?>
					<table class="ratings-list" cellspacing="0">
						<tbody>
							<?php foreach ($_review->getRatingVotes() as $_vote): ?>
							<tr>
								<td class="label"><strong><?php echo $_vote->getRatingCode() ?></strong></td>
								<td>
									<div class="rating-box">
										<div class="rating" style="width: <?php echo $_vote->getPercent() ?>%;"></div>
									</div>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt(), 'long')) ?></p>
					<?php
						echo $this->getChild('advancedreviews_proscons_indicator')->setReviewId( $_review->getId() )->toHtml();
						echo $this->getChild('advancedreviews_recommend_indicator')->setReviewId( $_review->getId() )->toHtml();
						echo $this->getChild('advancedreviews_footer')->setReviewId( $_review->getId() )->toHtml();
					?>
				</li>
			<?php endforeach; ?>
		</ol>
	</div>
    <?php endif; ?>
	<br/>
<?php endif; ?>
<?php else:?>
<h2><?php echo $this->__('Product Reviews') ?> 
<span style="float:right;">
<a href="<?php echo Mage::getBlockSingleton('review/helper')->getReviewsUrl() ?>" rel="iframe-680-505"  class="pirobox_gall1" title="Write A Review">
<?php echo $this->__('Write a review for this product') ?></a>
</span>
</h2> 
<p style="margin-top:10px;"><strong><?php echo $this->__('This product has no reviews.')?></strong></p>

<p class="no-rating"> 
<a href="<?php echo Mage::getBlockSingleton('review/helper')->getReviewsUrl() ?>" rel="iframe-680-530"  class="pirobox_gall1" title="Write A Review"><?php echo $this->__('Be the first to review this product') ?></a><br /> 
</p>



<?php endif; ?>
