<?php
$pdf_filepath = '';
$product = $this->getProduct(); 
if($pdffile = $product->getPdf()) { 
   $pdf_filepath = Mage::getModel('fileattributes/attribute_backend_file')->getFileUrl($pdffile);  
  ?>
<?php
   if(Mage::helper('mobiledetect')->isMobile()){ 
?>
    <div>
        <iframe src="//docs.google.com/gview?url=<?php echo $pdf_filepath?>&embedded=true" width="100%" height="100%" frameborder="0"></iframe>
    </div>
<?php } else {?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/pdfviewer/jquery.media.js'?>"></script> 
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/pdfviewer/jquery.metadata.js'?>"></script> 
    <script type="text/javascript">
     jQuery(function() {
            jQuery('a.media').media({width:100 + '%', height:100 + '%'});
			//{width:818, height:480}		
			
        });
    </script>
    <a class="media"  href="<?php echo $pdf_filepath?>" style="display:none;"></a> 
    <?php } ?>
<?php } else { ?>
    <?php echo "<script>window.location='".$product->getProductUrl()."';</script>"; ?>
<?php } ?>