<?php
/**
 * Downloadplus Admin Global Notification Template
 *
 * @author     PILLWAX Industrial Solutions Consulting
 * @category   Pisc
 * @package    Pisc_Downloadplus
 * @copyright  Copyright (c) 2014 PILLWAX Industrial Solutions Consulting (http://technology.pillwax.com/software)
 * @license    Commercial Unlimited License (http://technology.pillwax.com/software/license)
 * @version    0.1.0
 */
?>
<?php if ($message = $this->getMessage()) : ?>
    <div class="notification-global"><?php echo $message ?></div>
<?php endif; ?>
