<?php
$pdf_filepath = '';
$product = $this->getProduct(); 
if($pdffile = $product->getPdf()) { 
   $pdf_filepath = Mage::getModel('fileattributes/attribute_backend_file')->getFileUrl($pdffile);  
?>

    <div>
        <iframe src="http://docs.google.com/gview?url=<?php echo $pdf_filepath?>&embedded=true" style="width:820px; height:499px;" frameborder="0"></iframe>
    </div>
<?php } else { ?>
    <?php echo "<script>window.location='".$product->getProductUrl()."';</script>"; ?>
<?php } ?>