<?php 
$_crCollection = $this->getCatalogRequest();
 
?> 
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:80%;"><h3 class="<?php echo $this->getHeaderCssClass() ?>"><?php echo $this->helper('catalogrequest')->__('Catalog Request - View')?></h3></td>
        <td class="form-buttons"><?php echo $this->getChildHtml('back_button'); ?></td>
    </tr>
</table>
</div>
<div class="entry-edit">
<div class="entry-edit-head"><h4 >View Customer Details </h4></div>

  <fieldset>
  <table cellspacing="2" class="box-left"> 
       
			<?php if(sizeof($_crCollection) > 0):?> 
				 
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Firstname')?>: </strong></td> <td><?php echo $_crCollection->getFirstname();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Lastname')?>: </strong></td> <td><?php echo $_crCollection->getLastname();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('School Name')?>: </strong></td> <td><?php echo $_crCollection->getSchoolname();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Mailing Address')?>: </strong></td> <td><?php echo $_crCollection->getMailingAddress();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Appt. Unit')?>: </strong></td> <td><?php echo $_crCollection->getApptUnit();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('City')?>: </strong></td> <td><?php echo $_crCollection->getCity();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('State')?>: </strong></td> <td>
				<?php
				$region = $_crCollection->getRegion(); 
				if($regionId = $_crCollection->getRegionId()):
					$regionModel = Mage::getModel('directory/region')->load($regionId);
					$region = $regionModel->getName();
				endif;
				?>
				<?php echo $region;?></td>   </tr>  
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Country')?>: </strong></td> <td><?php echo $_crCollection->getCountryId();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Zipcode')?>: </strong></td> <td><?php echo $_crCollection->getZipcode();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Email')?>: </strong></td> <td><?php echo $_crCollection->getEmail();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Telephone')?>: </strong></td> <td><?php echo $_crCollection->getPhone();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Is Newsletter Signup')?>: </strong></td> <td><?php echo (($_crCollection->getSignUp()==1)?'Yes':'No');?></td>   </tr>
			<?php if($_crCollection->getSignUp()==1):?>	
			<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Resopnse of Listrak email.')?>: </strong></td> <td><?php echo $_crCollection->getListrakResponse();?></td>   </tr> 
			<?php endif;?>
		
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Which best describes to customer?[Market]')?>: </strong></td> <td><?php echo $_crCollection->getMarket();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('What subjects are you teaching?')?>: </strong></td> <td><?php echo $_crCollection->getSubject();?></td>   </tr>
				<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('How did you hear about us?')?>: </strong></td> <td><?php echo $_crCollection->getHearAbout();?></td>   </tr>
			 		<tr> <td><strong><?php echo $this->helper('catalogrequest')->__('Catalog Code')?>: </strong></td> <td><?php echo $_crCollection->getCatalogCode();?></td>   </tr> 
			<?php else:?>
				<tr> <td colspan="2"><strong><?php echo $this->helper('catalogrequest')->__('No Record Found')?></strong></td></tr>
			<?php endif;?>
			</table>
 
</fieldset></div>