<div class="page-title">
   <h1><?php echo Mage::helper('sales')->__('Track Your Order') ?></h1>
</div>
<div class="block-content">
   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
  <p> Find your web order ship date, shipping method, and tracking number (if available).</p>
 
       <ul class="form-alt">
           <li>
             
                   <label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <em style="color:#CC0000">*</em></label>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" /><br>

                   <span class="detail_text" style="clear:both; float:left; padding-bottom:10px;">(web order numbers are 9-digits)</span>
               </div>
           </li>
           <li style="clear:both; padding:10px 0;">
               <div class="input-box">
                   <b><?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?></b>
                </div>
           </li>
           <li style="clear:both; padding-bottom:10px;  ">
                   <label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em style="color:#CC0000">*</em></label>
               <div class="input-box" >
                   <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  />
               </div>
           </li>
           <li style="clear:both; padding-bottom:10px;">
		   <label class="required"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
                <div class="input-box" >
                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email">Email Address</option>
                       <option value="zip">ZIP Code</option>
                   </select>
               </div>
           </li>
           <li id="oar-email" style="clear:both;  padding-bottom:10px;">
               
                   <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <em style="color:#CC0000">*</em></label>
               <div class="input-box" >
                   <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"  />
               </div>
           </li>
           <li id="oar-zip" style="display:none;clear:both; padding-bottom:10px;">
              
                   <label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em style="color:#CC0000">*</em></label>
				<div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" />
               </div>
           </li>
           <li style="clear:both; padding-bottom:10px;">
               <div class="input-box" style="float:left;text-align:left; padding:0 0 0 158px;">
                   <button type="submit" title="Continue" class="button"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
               </div>
           </li>
           
           <li style="clear:both;">NOTE: Please allow 1-2 business days for order processing before attempting to track your order. </li>
       </ul>
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
