<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/magecoders/jquery-ui-1.8.2.custom.min.js'?>" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/magecoders/pirobox_extended.js'?>" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	jQuery().piroBox_ext({
	piro_speed : 700,
		bg_alpha : 0.5,
		piro_scroll : true // pirobox always positioned at the center of the page
	});
});
</script>
<?php $classArray = array('first','second','third','forth','fifth'); ?>
<?php $collection = $this->getCollection();?>
<div class="arrowlistmenu">
	<?php $type = '';?>
	<?php $i=0; $ct=count($collection);
	foreach($collection as $product){?>
	<?php $softproduct = $this->getProductCollectionBySoftwaredemo($product->getId());?> 
    <?php  if(trim($product->getValueId()) != trim($type)) { ?>
	    	<?php if($i!=0){?>
	    		</div>
	    	<?php } ?>
			<h3 class="menuheader expandable">
				<span class="<?php echo $classArray[$i]?>"><?php echo $product->getValue()." Software"; ?></span> 
				<strong class="<?php echo $classArray[$i]?>"><?php echo $this->__('%d Title',$this->getSoftwareDemosCount($product->getSubjectId()))?></strong>
			</h3>  
			<div class="categoryitems">
    	<?php $i++; } ?> 
		<div style="float:left; width:768px; padding-bottom:15px;">
        	<div class="soft_text_box1">
        		<?php if($product->getThumblineImg()):?>
        			<img width="75"  alt="<?php echo $product->getSoftname(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$product->getThumblineImg();  ?>"/>
        		<?php endif;?>
        	</div>
			<div class="soft_text_box2">
        		<h2><?php echo $product->getSoftname(); ?></h2>
    			<p><?php echo $product->getDescription(); ?></p>
        	</div>
        	<div class="soft_text_box3">
        		<a href="#soft_detail_<?php echo $product->getSoftwaredemosId(); ?>" rel="inline-502-402"  class="pirobox_gall1" title="Download Software"><?php echo $this->__('Download Demo!')?></a>
        	</div>
        </div>
        <div class="soft_detail" id="soft_detail_<?php echo $product->getSoftwaredemosId(); ?>" style="display:none; background:white;">
        	 <div class="soft_product_detail2">
        		<div class="soft_product_detail">
    				<span>
    					<?php if($product->getIconImg()):?>
    						<img width="36"  alt="<?php echo $product->getSoftname(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$product->getIconImg();  ?>"/>
    					<?php endif;?>
    				</span>
    				<h2><?php echo $product->getSoftname(); ?></h2>
    				<p><?php echo $product->getDescription(); ?></p>
    			</div>
    		    <div class="soft_product_image">
    	  			<img width="95" alt="<?php echo $product->getSoftname(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$product->getLargeImg();  ?>"/>
          			<p><?php echo $this->__('NOTE: This demo is of a discontinued version. The new, improved version is the same content with a visual upgrade and is already available for purchase. The new version demo is coming soon. Thank you for your understanding.')?></p>
    			</div>
    		</div>
    	
    	<div class="soft_product_detail1">
    	    <?php  foreach($softproduct as $softprod) {?>
               	<?php  if($softprod !='') { ?>
               	<?php $prod = Mage::getModel('catalog/product')->load($softprod['product_id']); ?>
	               	<?php if($prod->getIsSalable()){?>
	        		<div class="soft_associated_product">
	    				<div class="soft_product_name">
	        				<a href="<?php echo $prod->getProductUrl(); ?>" ><?php echo  $prod->getName(); ?></a>&nbsp;
	        				<?php if($prod->getGrade()):?>
	        					<span><?php echo $this->__('Grade(s)')?> <?php echo Mage::getModel('catalog/product')->getProductGrade($prod->getGrade());?></span>
	        				<?php endif;?>
	        			 </div>
	        			<div class="window">
	        			<?php if($wd = $prod->getWindowDownload()):?>
	        			<?php $wpath = Mage::getBaseDir('media').DS.'blfa_files/'.$wd; ?>
		            		<a href="<?php echo Mage::getBaseUrl('media').'blfa_files/'.$wd; ?>"  title="<?php echo $wd;?>">Download Exe</a>
			           		<span>( <?php echo Mage::helper('softwaredemos')->get_file_size($wpath ,'MB');  ?> )<br />
						            <?php echo $prod->getWindowPlatform()?>
						            <br/>
						            <?php echo $prod->getWindowRam()?>
				            </span>
				            <?php else:?>
				            <?php echo $this->__('Coming Soon')?>
			            <?php endif;?>
	    		  	 </div>
	        		<div class="mac">
	     			<?php if($md =$prod->getMacDownload()):?>
	     				<?php $mpath = Mage::getBaseDir('media').DS.'blfa_files/'.$md; ?>
		        			<a href="<?php echo $mpath; ?>"  title="<?php echo $md;?>"><?php echo $this->__('Download Exe')?></a>
		            		<span>( <?php echo Mage::helper('softwaredemos')->get_file_size($mpath,'MB');  ?> )<br />
			            		<?php echo $prod->getMacPlatform();?><br/>
								<?php echo $prod->getMacRam();?>		 
		            		</span>
	            		
			            <?php else:?>
				            <?php echo $this->__('Coming Soon')?>
	            		<?php endif;?>
	        		</div>
	    		</div>
	  		 	 <?php }?>
	  		  <?php }?>
   	 	<?php } ?>
     </div>
</div> 
 
<?php if($ct == $i ) {?>
  </div>
  <?php }?>
  <?php	$type = $product->getValueId();?>
  <?php } ?>   
    
	</div>

	<div class="arrowlistmenu">
		<h3 class="menuheader expandable"><span class="fifth"><?php echo $this->__('Full Version Software Demos')?></span></h3>
		<div class="categoryitems">
        <div class="categoryitems_text">
		<p><?php echo $this->__('Full version software demos are also available to schools, institutions, and companies. Preview orders must be on a purchase order or letterhead with an authorized signature. Preview orders are invoiced, but a full credit will be issued if the product is returned in resalable condition within thirty days of receipt. All of our products come with a sixty-day')?><br />

<a href="<?php echo $this->getUrl('') ?>guarantee">money-back guarantee!</a>
</p>
        </div>
        </div>
</div>
</div>


 

<script type="text/javascript">
function launchDownload(softid)
{
	jQuery('soft_detail_'+softid).show();
}
function hideDownload(softid)
{
	jQuery('soft_detail_'+softid).show();
}
</script>



