<?php
/**
 * Link for RSS Feed on Additional Downloads of Downloadable Products List
 *
 * @see Pisc_Downloadplus_Block_Rss_Updates
 */
?>
<?php if ($this->isRssAvailable()): ?>
<div class="clear"></div>
<a href="<?php echo $this->getRssLink() ?>" class="link-feed right downloadplus-link-feed"><?php echo $this->__('Subscribe to RSS Feed on all free additional downloads of all Products') ?></a>
<div class="clear"></div>
<?php endif; ?>
