<p><link rel="stylesheet" href="http://10.16.16.191/criticalthinking/skin/frontend/default/newcritical/css/jquery-ui.css"></p>

    <p><img src="http://10.16.16.191/criticalthinking/media/wysiwyg/header_test_prep.jpg" alt="Test Preparation Guide"><br></p><div id="accordian-state" class="row">
        <h3 class="large_title_blue">State Assessments:</h3>
        <div class="state_assessments_box col-v6">

            <ul class="description_text details_link">
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=153">Arizona's Instrument to Measure Standards (AIMS)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=154">California High School Exit Exam (CAHSEE)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=155">California Standardized Testing and Reporting (STAR)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=156">Colorado Standard and Assessment Program (CSAP)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=157">Connecticut Mastery Test (CMT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=347">District of Columbia Comprehensive Assessment System (DCCAS)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=158">Florida State Assessment (FSA)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=159">Georgia Criterion-Referenced Competency Tests (CRCT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=160">Illinois Standards Achievement Test (ISAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=161">Indiana Statewide Testing for Educational Progress (ISTEP+)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=162">Kansas State Assessments</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=163">Louisiana Educational Assessment Program (LEAP)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=164">Louisiana Graduation Exit Exam (GEE)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=165">Massachusetts Comprehensive Assessment System (MCAS)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=166">Michigan Educational Assessment Program (MEAP)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=167">Minnesota Comprehensive Assessment (MCA-II)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=168">New York State English Language Arts (ELA) Test</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=149">New York State Mathematics Test</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=348">NYC's Specialized High School Admissions Test (SHSAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=304">North Carolina Competency Test </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=150">North Carolina End of Grade Tests</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=151">Ohio Achievement Tests</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=152">Palmetto Assessment of State Standards (PASS) </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=299">South Carolina STAR Performance Task Assessment </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=146">State of Texas Assessments of Academic Readiness (STAAR) (replaced the Texas Assessment of Knowledge and Skills (TAKS))</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=147">Virginia Standards of Learning (SOL)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=148">WA Measurements of Student Progress (MSP)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?state_assessments=145">Washington High School Proficiency Exam (HSPE)</a></li>

            </ul>
            <p class="detail_text">For products to prepare for the Plano Academic and Creative Education (PACE) Assessment, refer to the CogAT&reg; and NNAT&reg; links to the right. </p>
        </div>
        <h3 class="large_title_blue">Achievement Tests:</h3>
        <div class="state_assessments_box col-v6">

            <ul class="description_text details_link">
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=169">ACT Assessment&reg; (ACT&reg;)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=170">Bracken School Readiness Assessment&reg; (BSRA&reg;)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=171">California Achievement Test (CAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=172">California Critical Thinking Skills Test (CCTST)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=173">Cognitive Abilities Test&trade; (CogAT&reg;)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=174">Cornell Critical Thinking Tests (CCTT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=303">Early Childhood Admissions Assessment (ECAA) by Educational Records Bureau (ERB) </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=178">GED Tests</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=177">Gifted and Talented Education (GATE) / Talented and Gifted (TAG)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=179">Graduate Record Examination (GRE)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/hip">High Impact Player Assessment (HIP)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=302">Independent School Entrance Exam (ISEE) </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=181">InView Test</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=182">Iowa Tests of Basic Skills&reg; (ITBS&reg;)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=183">Law School Admissions Test (LSAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=184">Medical College Admissions Test (MCAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=185">Metropolitan Achievement Tests&reg; Eighth Edition</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=186">NNAT&reg; Assessment or Naglieri Nonverbal Ability Test&reg; </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=187">OLSAT&reg;-8 Assessment or Otis-Lennon School Ability Test&reg;</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=337">Partnership for Assessment of Readiness for College and Careers (PARCC)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=188">Peabody Picture Vocabulary Test&trade; (PPVT&trade;-R)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=189">Primary Test of Cognitive Skills&trade; (PTCS)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=190">RPM&reg; Assessment or Raven's Progressive Matrices&reg;</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=301">Scantron Performance Series&reg; </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=191">Scholastic Assessment Test (SAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=192">School and College Abilities Test (SCAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=300">Screening Assessment for Gifted Elementary and Middle School Students, 2nd Edition (SAGES-2) </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=193">Secondary School Admissions Test (SSAT)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=194">Stanford-Binet Intelligence Scale Fourth &amp; Fifth Editions</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=195">Stanford 10 or Stanford Achievement Test&trade; </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=196">TerraNova, Third Edition, formerly CTBS and CAT/6 </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=197">WISC&reg;-IV &amp; older versions or Wechsler Intelligence Scale for Children&reg; </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=198">WPPSI&trade; Assessment or Wechsler Preschool and Primary Intelligence Scale&trade;</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=199">Wide Range Achievement Test (WRAT, WRAT-3)</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?achievement_tests=200">Woodcock-Johnson&reg; Tests of Cognitive Ability (WJ-R&reg;)</a></li>

            </ul>
        </div>
    </div><p></p>
    <p style="clear: both; padding-top: 20px;" class="description_text">Higher test scores guaranteed on state assessments and achievement tests.</p>
    <hr>
    <div class="row" id="accordian-testprep"><h3 class="large_title_blue">Test Prep Bundles<span class="description_text"> - <strong>Save 10%!</strong></span></h3>
        <div class="state_assessments_box col-v6">

            <ul class="description_text details_link">
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result?name=olsat&amp;product_type[]=125">Test Prep Bundles for the OLSAT&reg; Assessment</a> <span class="detail_text">by Grade</span></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result?name=cogat&amp;product_type[]=125">Cognitive Abilities Test&trade; (CogAT&reg;) Prep Bundles</a> <span class="detail_text">by Grade</span></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result?name=itbs&amp;product_type[]=125">Iowa Test of Basic Skills&reg; (ITBS&reg;) Prep Bundles</a> <span class="detail_text">by Grade</span></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result?name=wisc&amp;product_type[]=125">Test Prep Bundles for the WISC&reg; Assessment</a><span class="detail_text"> by Grade</span></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result?name=wppsi&amp;product_type[]=125">Test Prep Bundles for the WPPSI&trade; Assessment</a><span class="detail_text"> by Grade</span></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result?name=nnat&amp;product_type[]=125">Test Prep Bundles for the Naglieri Nonverbal Ability Test&reg;</a> <span class="detail_text">by Grade</span></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/tag/product/list/tagId/9">Gifted and Talented Education (GATE) / Talented and Gifted (TAG) Test Prep Bundles</a><span class="detail_text"> by Grade</span></li>
                <li><strong><a href="http://10.16.16.191/criticalthinking/index.php/catalogsearch/advanced/result/?subject[]=294&amp;product_type[]=125">View All Bundles</a></strong></li>
            </ul>
        </div> <h3 class="large_title_blue">Test Prep Guides</h3>
        <div class="state_assessments_box col-v6">

            <ul class="description_text details_link">
                <li><a href="http://10.16.16.191/criticalthinking/index.php/articles/test-preparation-practice-for-olsat-assessment" title="Test Prep Guide for the Otis-Lennon School Ability Test® (OLSAT®)">Otis-Lennon School Ability Test&reg; (OLSAT&reg;) Assessment&nbsp;</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/articles/test-preparation-practice-for-cogat-assessment" title="Test Prep Guide for the Cognitive Abilities Test™ (CogAT®) ">Cognitive Abilities Test&trade; (CogAT&reg;) Assessment</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/articles/test-preparation-practice-for-itbs-assessment" title="Test Prep Guide for the Iowa Test of Basic Skills® (ITBS®)">Iowa Tests of Basic Skills&reg; (ITBS&reg;) Assessment</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/articles/test-preparation-practice-for-nnat-assessment" title=" 	Test Prep Guide for the Naglieri Nonverbal Ability Test® (NNAT®)">Naglieri Nonverbal Ability Test&reg; (NNAT&reg;) Assessment </a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/articles/test-preparation-practice-for-wisc-assessment" title="Test Prep Guide for the Wechsler Intelligence Scale for Children® (WISC®)">Wechsler Intelligence Scale for Children&reg; (WISC&reg;) Assessment</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/articles/test-preparation-practice-for-wppsi-assessment" title="Test Prep Guide for the Wechsler Preschool and Primary Scale of Intelligence™ (WPPSI™)">Wechsler Preschool and Primary Intelligence Scale&trade; (WPPSI&trade;) Assessment</a></li>
                <li><a href="http://10.16.16.191/criticalthinking/index.php/articles/test-preparation-practice-for-gate-and-tag-assessments" title="Test Prep Guide for the Gifted and Talented Education (GATE) and Testing Talented and Gifted (TAG)">Gifted and Talented Education (GATE) / Talented and Gifted (TAG) Tests</a></li>
            </ul>
        </div></div>
    <div class="col-v12">
        <p style="clear: both; padding-top: 20px;" class="description_text">Bundles are sold as discounted items with their own product numbers (different from the individual items which make up a bundle). Individual items purchased separately over a period of time are not eligible for the discounted bundle prices.</p>
        <p class="description_text">If you are not completely satisfied with your purchase, we will gladly help you with an exchange, credit, or refund. Return information is attached to every packing slip.</p>
        <p style="clear: both; padding-top: 30px;" class="detail_text">* The correlations are meant to show that skills assessed in a particular test are addressed in a product from The Critical Thinking Company. We do not claim that our materials match up exactly to each test or teach all the skills measured in a particular assessment. The recommendations made here are determined by The Critical Thinking Co.&trade; and are not endorsed or certified by the author or publisher of each test. While the recommended items will help prepare students to master the skills tested, they do not reflect the actual test items on any given test.</p>
        <p class="detail_text">The Critical Thinking Co.&trade; is the official publisher of the <a href="#">Cornell Critical Thinking Tests&trade; (CCTT&trade;)</a> and the <a href="#">James Madison Tests of Critical Thinking&trade; (JMTCT&trade;)</a>.</p>
        <p style="margin-bottom: 20px;" class="detail_text">Otis-Lennon School Ability Test&reg;,OLSAT&reg;, Wechsler Intelligence Scale for Children&reg;,WISC&reg;, WPPSI&trade;, Metropolitan Achievement Tests&reg;, Raven's Progressive Matrices&trade;, Naglieri Nonverbal Ability Test&reg;, and NNAT&reg; are trademarks, in the US and /or other countries, of Pearson Education, Inc. or its affiliate(s), or their licensors, which do not endorse these products.</p>
    </div>


<script src="http://10.16.16.191/criticalthinking/skin/frontend/default/newcritical/js/jquery-ui.js" type="text/javascript"></script>

    <script type="text/javascript">

        jQuery(document).ready(function() {

            jQuery.noConflict();
            if ( jQuery(window).width() < 768) {
                jQuery( "#accordian-testprep" ).accordion();
                jQuery( "#accordian-state" ).accordion();
            }

        } );
        </script>