<?php
$pdf_filepath = '';
$product = $this->getProduct(); 
if($pdffile = $product->getPdf()) { 
   $pdf_filepath = Mage::getModel('fileattributes/attribute_backend_file')->getFileUrl($pdffile);  
?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/pdfviewer/jquery.media.js'?>"></script> 
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/pdfviewer/jquery.metadata.js'?>"></script> 
<script type="text/javascript">
 jQuery(function() {
        jQuery('a.media').media({width:818, height:480}); 
    });
</script>
<a class="media"  href="<?php echo $pdf_filepath?>" style="display:none;"></a> 
    
<?php } else { ?>
    <?php echo "<script>window.location='".$product->getProductUrl()."';</script>"; ?>
<?php } ?>