<?php
/**
 * @see Pisc_Downloadplus_Block_Adminhtml_Catalog_Product_Edit_Tab_Settings
 */

?>
<!--
<script type="text/javascript" src="<?php echo $this->getJsUrl('pisc/downloadplus/adminhtml/catalog/product/edit/form.js') ?>"></script>
-->

<?php echo $this->getChildHtml('accordion-links'); ?>

<script type="text/javascript">
//	downloadplusForm = new downloadplusAdminForm();
//	downloadplusForm.bindFieldsChange(downloadplusForm.getDataElements());
</script>
