<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div> 
<?php $formData = Mage::getSingleton('core/session')->getFormData();?>
    <div class="page-title">
    <span class="tred"><br>Free Education Newsletter </span>
    <h1><?php echo Mage::helper('newsletter')->__('Sign Up Today!') ?></h1>
</div>
 <p class="description_text">
	<?php echo $this->__('The Critical Thinking Co.\'s FREE Monthly Education Newsletter features free activities, new products, special offers, teaching tips, and more! ')?>
</p>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
          <div class="fieldset">
            <div class="newsletter-from">
	          <ul>
		   		  <li>
		   		  <div class="field">
	                    <label for="name" ><?php echo Mage::helper('newsletter')->__('First Name:') ?><span class="required">*</span></label>
	                    <div class="input-box">
	
	                      <input class="input-text required-entry" name="firstname" id="firstname"  type="text" value="<?php echo  ($formData['firstname']?$formData['firstname']:'')  ?>" />
	                    </div>
	                </div>
			        </li>
			        <li> 
			         <div class="field">
			        		<label for="lastname"><?php echo Mage::helper('newsletter')->__('Last Name:') ?><span class="required">*</span></label>
				         	<div class="input-box">
					        	<input class="input-text required-entry " name="lastname" id="lastname"  type="text" value="<?php echo  ($formData['lastname']?$formData['lastname']:'')  ?>" />
					        </div>   
				        </div>   
				     </li> 
			        <li> 
			         	<div class="field">
			        		<label for="lastname"><?php echo Mage::helper('newsletter')->__('Email:') ?><span class="required">*</span></label>
			        		<div class="input-box">
            		   			<input type="text" name="email" id="newsletter" value="<?php echo  ($formData['email']?$formData['email']:'')  ?>" title="<?php echo $this->__('Email') ?>" class="input-text required-entry validate-email" />
            		   		</div>
            		   	</div>
            		</li>
           
			        <li>  
			         	<div class="field">
			        		<label for="lastname"><?php echo Mage::helper('newsletter')->__('Position:') ?><span class="required">*</span></label>
			        		<div class="input-box">
	        	                 <input name="position" value="Parent" <?php echo  (($formData['position'] == 'Parent')?"checked='checked'":'')  ?> type="radio"><?php echo $this->__('Parent')?><br>
    		                     <input name="position" value="Home Educator" type="radio" <?php echo  (($formData['position'] == 'Home Educator')?"checked='checked'":'')  ?>><?php echo $this->__('Home Educator')?><br>
                          		 <input name="position" value="Classroom Educator" <?php echo  (($formData['position'] == 'Classroom Educator')?"checked='checked'":'')  ?>type="radio"><?php echo $this->__('Classroom Educator')?><br>
            		   		</div>
            		   	</div>
            		</li>
            		<li>
            			<div align="left">
                            	<span class="promotion_error">* </span><span class="detail_text_red">(required)</span>
	                			<p><?php echo $this->__('We respect your privacy. E-mail addresses are not released to third parties. Instructions for removal come with every e-mail.')?></p>
						</div>
            		</li>
            		   
					 <?php echo $this->getChildHtml('form.additional.info'); ?> 
	           </ul>
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button_subscribe"><?php echo $this->__('Subscribe') ?></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>

