<?php
$countryCode = Mage::getSingleton('geoip/country')->getCountry();

$isEuropean = Mage::helper('geoip')->isEuropean($countryCode);


?>
<div class="customsubscribe-two">
    <div class="container">
        <div class="head">
 <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customsubscribe2_header')->toHtml(); ?>    
</div>

<div class="newslatter_form_box-two">

	<div class="newslatter_form_box-two_left">
		<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
		<?php $formData = Mage::getSingleton('core/session')->getFormData();?>

		 <div class="form-text">

        

  
 <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customsubscribe2_top_text')->toHtml(); ?>
        </div>

		<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
			<div class="fieldset">
<?php if($this->getRequest()->getParam('supply'))
				{
					$supply = $this->getRequest()->getParam('supply');
				}else {
					$supply = (isset($formData['supply'])?$formData['supply']:'');
				}?>
				<input type="hidden" name="supply" id="supply" value="<?php echo $supply ?>"/>
				<div class="newsletter-from">

					<ul>
						<!--li>
							<div class="field">
								<label for="name" ><?php echo Mage::helper('newsletter')->__('First Name:') ?><span class="required">*</span></label>
								<div class="input-box">

									<input class="input-text required-entry" style="width:256px;" name="firstname" id="firstname"  type="text" value="<?php echo  (isset($formData['firstname'])?$formData['firstname']:'')  ?>" />
								</div>
							</div>
						</li>
						<li>
							<div class="field">
								<label for="lastname"><?php echo Mage::helper('newsletter')->__('Last Name:') ?><span class="required">*</span></label>
								<div class="input-box">
									<input class="input-text required-entry " style="width:256px;" name="lastname" id="lastname"  type="text" value="<?php echo  (isset($formData['lastname'])?$formData['lastname']:'')  ?>" />
								</div>
							</div>
						</li-->
						<li>
							<div class="field">
								<label for="lastname">&nbsp</label>
								<div class="input-box">
									<input placeholder="Your best email address" type="text" name="email" id="overridenewsletter" style="width:256px;" value="<?php echo  (isset($formData['email'])?$formData['email']:'')  ?>" title="<?php echo $this->__('Email') ?>" class="customsybemailfield input-text required-entry validate-email-custom" />
								</div>
							</div>
						</li>


						<!--li>
							<div class="field">
								<label for="best_describe"><?php echo Mage::helper('catalogrequest')->__('Which best describes you?') ?><span class="required">*</span></label>

								<div class="input-box">
									<select  class="input-text required-entry" name="position" size="1">
										<option value="">-- Please Select --</option>
										<?php $arrMarket = array('Parent','Home Educator', 'Classroom Educator'); ?>
										<?php foreach($arrMarket as $key => $value): ?>
											<option value="<?php echo $value ?>" <?php echo (($formData['position'] == $value)?'selected="selected"':'')?>>
												<?php echo $value ?>
											</option>
										<?php endforeach; ?>
									</select></div>
							</div>

						</li-->
						<li>
							<div class="field">
								<label class="desktop-enable" for="lastname">&nbsp<!--span class="required">*</span--></label>
								<div class="input-box radio customsubsccheckboc">

									
									<div class="checkbox"><input id="1email" name="email_list[]" value="2405007" type="checkbox" <?php echo ((in_array('2405007',$formData['email_list']))?'checked="checked"':'')?> ><label for="1email" class="label"><?php echo $this->__('Grade PreK')?><?php echo $this->__(' Puzzle of the Week')?></label></div><br>
									<div class="checkbox"><input id="1emaillist" name="email_list[]" value="2405008" type="checkbox" <?php echo ((in_array('2405008',$formData['email_list']))?'checked="checked"':'')?> ><label for="1emaillist" class="label"><?php echo $this->__('Grades K-2')?><?php echo $this->__(' Puzzle of the Week')?></label></div><br>
									<div class="checkbox"><input id="1emaillist2" name="email_list[]" value="2405009" type="checkbox" <?php echo ((in_array('2405009',$formData['email_list']))?'checked="checked"':'')?> ><label for="1emaillist2" class="label"><?php echo $this->__('Grades 3-5')?><?php echo $this->__(' Puzzle of the Week')?></label></div><br>
									<div class="checkbox"><input id="1emaillist3" name="email_list[]" value="2405010" type="checkbox" class="validate-one-required-by-name" <?php echo ((in_array('2405010',$formData['email_list']))?'selected="selected"':'')?>><label for="1emaillist3" class="label"><?php echo $this->__('Grades 6-8')?><?php echo $this->__(' Puzzle of the Week')?></label></div><br>
<span style="font-size: 11px;color:#3366CC;line-height: 16px;border-bottom: 1px solid #ccc;padding-bottom: 3px;margin: 3px 0 5px;display: inline-block;">Each puzzle contains a link to our best sale offer.</span></br>
<div class="checkbox"><input id="1emaillist4" name="email_list[]" value="2405405" type="checkbox" <?php echo ((in_array('2405405',$formData['email_list']))?'checked="checked"':'')?> ><label for="1emaillist4" class="label"><?php echo $this->__('Bi-Monthly Best Sale Alerts')?></label></div><br>


								</div>
							</div>
						</li>
						
					</ul>
				</div>
				<div class="button-set-box" style="padding: 10px 0 8px 175px;">
					<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button-form"><?php echo $this->__('Subscribe') ?></button>
				</div>
<?php if($isEuropean): ?>

							<div class="field privacy-policy-sec">
<a target="_blank" class="non-underline" href="<?php echo Mage::getUrl('site-policies') ?>"><?php echo $this->__('Privacy Policy') ?></a>

							</div>
						
<?php endif; ?>
			</div>
		</form>

		<script type="text/javascript">
			//<![CDATA[
			var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');

			//]]>
		</script>

	</div>

	<?php // echo $this->getLayout()->createBlock('cms/block')->setBlockId('customsubscribe2_right_image')->toHtml(); ?> 


</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customsubscribe2_bottom_text')->toHtml(); ?> 
</div>
</div>


