<?php
/**
 * @see Pisc_Downloadplus_Block_Adminhtml_Catalog_Product_Edit_Tab_Detail_Files
 */

$_product = $this->getProduct();
$_detail = $this->getDetail();
$_filename = $this->getFileBasename();
$_key = $this->getDetailArea().'_'.$_detail->getId();
?>

<div class="fieldset" id="group_fields_downloadplus_<?php echo $this->getDetailArea(); ?>_<? echo $_detail->getId(); ?>">

<input type="hidden" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][id]" value="<?php echo $_detail->getId(); ?>" />
<input type="hidden" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][file]" value="<?php echo $this->getFileWithType(); ?>" />
<input type="hidden" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][area]" value="<?php echo $this->getDetailArea(); ?>" />
<div class="hor-scroll">
<table cellspacing="0" class="form-list">
	<tbody>
		<?php if (!Mage::app()->isSingleStoreMode()): ?>
		<tr>
		    <td class="scope-label">
            <?php if($_product->getStoreId()) { echo $this->__('[STORE VIEW]'); } ?>
		    </td>
            <td class="value use-default">
            <?php if($_product->getStoreId()): ?>
                <input id="link_title_default_<?php echo $_key; ?>" type="checkbox" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][use_default]" value="1" onclick="toggleValueElements(this, $('link_title_default_<?php echo $_key; ?>'))" <?php echo $_detail->getUsedDefault()?'checked="checked"':'' ?> />
                <label class="normal" for="link_title_default"><?php echo $this->__('Use Default Value') ?></label>
            <?php endif; ?>
            </td>
        </tr>
		<?php endif; ?>
    	<tr>
        	<td class="label"><label for="product_downloadplus_detail_relation_<?php echo $_key; ?>"><?php echo $this->__('Related To'); ?></label></td>
    		<td class="value toggleValueElements">
    			<?php echo $this->getFileRelation($_product->getStoreId()!=null); ?>
    		</td>
		    <td id="note_downloadplus_detail_relation_<?php echo $_key; ?>"></td>
    	</tr>
    	<tr>
        	<td class="label"><label for="product_downloadplus_detail_filedate_<?php echo $_key; ?>"><?php echo $this->__('Size & Date'); ?></label></td>
    		<td class="value toggleValueElements">
    			<input id="product_downloadplus_detail_filedate_<?php echo $_key; ?>" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][filedate]" value="<?php echo $_detail->getSizeFormatted().', '.date('Y-m-d - H:i:s', $_detail->getTimestamp()); ?>" class="input-text" disabled="disabled" type="text"/>
    		</td>
		    <td id="note_downloadplus_detail_filedate_<?php echo $_key; ?>"></td>
    	</tr>
    </tbody>
</table>
<table cellspacing="0" class="form-list" id="<?php echo $_key ?>">
	<tbody>
    	<tr>
        	<td class="label"><label for="product_downloadplus_detail_fileversion_<?php echo $_key; ?>"><?php echo $this->__('Version'); ?></label></td>
    		<td class="value">
    			<input id="product_downloadplus_detail_fileversion_<?php echo $_key; ?>" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][fileversion]" value="<?php echo $_detail->getVersion(); ?>" class="input-text" type="text" <?php echo ($_product->getStoreId()&&$_detail->getUsedDefault())?'disabled="disabled"':'' ?>/>
    		</td>
		    <td id="note_downloadplus_detail_fileversion_<?php echo $_key; ?>"></td>
    	</tr>
    	<tr>
        	<td class="label"><label for="product_downloadplus_detail_filedescription_<?php echo $_key; ?>"><?php echo $this->__('Description'); ?></label></td>
    		<td class="value">
    			<textarea id="product_downloadplus_detail_filedescription_<?php echo $_key; ?>" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][filedetail]" class="textarea downloadplus-detail-filedetail" <?php echo ($_product->getStoreId()&&$_detail->getUsedDefault())?'disabled="disabled"':'' ?>><?php echo $_detail->getDetail(); ?></textarea>
    		</td>
		    <td id="note_downloadplus_detail_filedescription_<?php echo $_key; ?>"></td>
    	</tr>
    	<?php if ($this->getDetailArea()!='active'): ?>
    	<tr>
        	<td class="label"><label for="product_downloadplus_detail_hidden_<?php echo $_key; ?>"><?php echo $this->__('Hide this File on Frontend'); ?></label></td>
    		<td class="value">
    			<input id="product_downloadplus_detail_hidden_<?php echo $_key; ?>" name="downloadplus[detail][<?php echo $_detail->getId(); ?>][hidden]" value="1" class="downloadplus-detail-hidden" type="checkbox" <?php echo ($_detail->isHidden())?'checked="checked"':'' ?>/>
    		</td>
		    <td id="note_downloadplus_detail_hidden_<?php echo $_key; ?>"></td>
    	</tr>
    	<?php endif; ?>
    </tbody>
</table>
</div>

</div>