<div id="homepage_scrolling_features">
<h3>What Other Customers Have Recently Purchased</h3>


<img src="<?php echo $this->getSkinUrl('images/homepage_feature_left_arrow.jpg')?>" alt="" class="navigation_arrow" onmouseover="homepageScrollStart('right')" onmouseout="homepageScrollStop()" />

<div id="homepage_scrolling_stage">
<div id="homepage_scrolling_slider">
<?php
$recentSoldItems = $this->getRecentlySoldItems();
if(sizeof($recentSoldItems)>0)
{?>
	<table id="homepage_scrolling_slider_table" border="0" width="1000" cellpadding="0" cellspacing="0"><tbody><tr>
	<?php	foreach ($recentSoldItems as $item)	{?>
		<td style="width:116px;">
			 <a href="<?php echo $item->getProductUrl() ?>" title="<?php echo $this->stripTags($item->getName()) ?>" class="product-image">
			 	<img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(110); ?>" width="110" height="135" alt="<?php echo $this->stripTags($item->getName()) ?>" />
			 	</a> 
		</td> 
        
	<?php } ?>
    <td style="padding-right:6px;"></td>
	</tr></tbody></table> 
<?php } ?>

</div>
</div>

<img src="<?php echo $this->getSkinUrl('images/homepage_feature_right_arrow.jpg')?>" alt="" class="navigation_arrow" onmouseover="homepageScrollStart('left')" onmouseout="homepageScrollStop()" />

 </div>



<script type="text/javascript">
	//<![CDATA[
function goToSeries(seriesId)
	{
		if( seriesId > 0){ window.location='/series/'+seriesId+'.html' };
	}
	
	function homepageScroll()
	{
		var inc = (homepageScroll.direction == 'left') ? -5 : 5 ;
		var newpos = parseInt(jQuery('#homepage_scrolling_slider').css('left')) + inc;
		if (
			(homepageScroll.direction == 'right' && newpos > 0) ||
			(homepageScroll.direction == 'left' && newpos < (homepageScroll.scrollWidth * -1))
		)
		{
			homepageScrollStop();
		}
		else
		{
			jQuery('#homepage_scrolling_slider').css('left',newpos);
		}
	}

	function homepageScrollStart(direction)
	{
		//alert($('#homepage_scrolling_slider_table').width());
		homepageScroll.direction = direction;
		homepageScroll.scrollWidth = jQuery('#homepage_scrolling_slider_table').width() - jQuery('#homepage_scrolling_stage').width();
		homepageScroll.timer = window.setInterval('homepageScroll()',35);
	}

	function homepageScrollStop()
	{
		window.clearInterval(homepageScroll.timer);
	}
	//]]>
</script>
 


