<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>We will back soon</title>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:300,600' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale = 1.0, user-scalable = no">
    <style>
        body{font-family: 'Open Sans', sans-serif; background: #e9e5e2; color: #665b52;text-align: center;line-height: 28px;margin: 0; padding: 0;}
        h1{  color: #665b52;font-size: 36px;font-family: 'Open Sans', sans-serif; }
        .wrapper{ height: 100%; position: fixed; width: 100%;}
        .content{display: inline-block; vertical-align: middle; position: relative; padding: 20px;}
        a { color: #e05050; text-decoration: none; }
        a:hover { color: #333; text-decoration: none; }
    </style>
</head>
<body>
<div class="wrapper">
    <div class="content">
        <p><img src="http://www.criticalthinking.com/skin/frontend/default/critical/images/logo.jpg" style="max-width: 280px" /></p>
        <p style="max-width: 500px; margin: 0 auto;">We are currently down for maintenance and we expect to be back online in a some time. For urgent enquiries, please contact us on <a href="mailto:info@criticalthinking.com">info@criticalthinking.com</a> or call us on <a href="tel:800-458-4849">800-458-4849</a>.</p>
       

    </div><!-- header ended-->
    <div style="display: inline-block;vertical-align: middle;height: 100%;"></div>
</div>

</body>
</html>
