<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/magecoders/jquery-ui-1.8.2.custom.min.js'?>" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/magecoders/pirobox_extended.js'?>" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	jQuery().piroBox_ext({
	piro_speed : 700,
		bg_alpha : 0.5,
		piro_scroll : true // pirobox always positioned at the center of the page
	});
});
</script>
<?php 
$classArray = array('first','second','third','forth','fifth'); 
$collection = $this->getCollection();
?>
<div class="arrowlistmenu">

<?php 
$type = '';
$i=0;
$ct=count($collection);
foreach($collection as $product)
{
	$softproduct = explode(',', $product->getSoftwaredemoProductId());
?> 
    <?php  
    if(trim($product->getValueId()) != trim($type)) { 
		     if($i!=0){
				 echo "</div>";
			 }  
			
	 ?>
		<h3 class="menuheader expandable"><span class="<?php echo $classArray[$i]?>"><?php echo $product->getValue()." Software"; ?></span> <strong class="<?php echo $classArray[$i]?>"><?php echo $this->__('%d Title',$this->getSoftwareDemosCount($product->getSubjectId()))?></strong></h3>
		<div class="categoryitems">
    <?php  }
	
	 ?> 
	<div style="float:left; width:768px; padding-bottom:15px;">
        <div class="soft_text_box1"><img width="75"  alt="<?php echo $product->getSoftname(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$product->getThumblineImg();  ?>"/></div>
		<div class="soft_text_box2">
        <h2><?php echo $product->getSoftname(); ?></h2>
    	<p><?php echo $product->getDescription(); ?></p>
        </div>
        <div class="soft_text_box3">
        <a href="#soft_detail_<?php echo $product->getSoftwaredemosId(); ?>" rel="inline"  class="pirobox_gall1" title="Download Software">Download Demo!</a>
        </div>
        </div>
        
<?php /*?>id="soft_detail_<?php echo $product->getSoftwaredemosId(); ?>" <?php */?>
<div class="soft_detail" id="soft_detail_<?php echo $product->getSoftwaredemosId(); ?>" style="display:none; background:white;">
        
        
         <div class="soft_product_detail2">
        <div class="soft_product_detail">
    	<span><img width="36"  alt="<?php echo $product->getSoftname(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$product->getIconImg();  ?>"/></span>
    	<h2><?php echo $product->getSoftname(); ?></h2>
    	<p><?php echo $product->getDescription(); ?></p>
    </div>
    
    <div class="soft_product_image">
    	  <img width="95" alt="<?php echo $product->getSoftname(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$product->getLargeImg();  ?>"/>
          <p>NOTE: This demo is of a discontinued version. The new, improved version is the same content with a visual upgrade and is already available for purchase. The new version demo is coming soon. Thank you for your understanding.</p>
    </div>
    </div>
    
    <div class="soft_product_detail1">
    
         <?php
		
	  
	  foreach($softproduct as $softprod)
	  {
	
	   if($softprod !='')
	   {
	   $prod = Mage::getModel('catalog/product')->load($softprod); 
	  
	  ?>
        <div class="soft_associated_product">
    	<div class="soft_product_name">
        <a href="<?php echo $prod->getProductUrl(); ?>" ><?php echo  $prod->getName(); ?></a>&nbsp;
        <span>Grade(s) 3rd-6th</span>
        </div>
        <div class="window">
        	<?php
			$attributeName = 'window_download';
			$wd = Mage :: getModel('softwaredemos/softwaredemos')->getSoftAttributeVal($prod,$attributeName);
			$wpath = Mage::getBaseDir('media').DS.'blfa_files/'.$wd;
			 ?>
            <a href="<?php echo Mage::getBaseUrl('media').'blfa_files/'.$wd; ?>"  title="<?php echo $wd;?>">Download Exe</a>
           <span>
           
           ( 
            <?php echo Mage::helper('softwaredemos')->get_file_size($wpath ,'MB');  ?> )
           
            <br />
            
            <?php
			$attributeName = 'window_platform';
			echo $wp = Mage :: getModel('softwaredemos/softwaredemos')->getSoftAttributeVal($prod,$attributeName);
						$attributeName = 'window_ram';
			echo "<br/>".$wm = Mage :: getModel('softwaredemos/softwaredemos')->getSoftAttributeVal($prod,$attributeName);			 ?>
            
            </span>
          
        </div>
        <div class="mac">
     	<?php
			$attributeName = 'mac_download';
			$md = Mage :: getModel('softwaredemos/softwaredemos')->getSoftAttributeVal($prod,'mac_download');
			$mpath = Mage::getBaseDir('media').DS.'blfa_files/'.$md;
			 ?>
            <a href="<?php echo $mpath; ?>"  title="<?php echo $md;?>">Download Exe
            </a>
            <span>
            ( 
            <?php echo Mage::helper('softwaredemos')->get_file_size($mpath,'MB');  ?> )
          
            <br />
            <?php
			$attributeName = 'mac_platform';
			echo $wp = Mage :: getModel('softwaredemos/softwaredemos')->getSoftAttributeVal($prod,$attributeName);
						$attributeName = 'mac_ram';
			echo "<br/>".$wm = Mage :: getModel('softwaredemos/softwaredemos')->getSoftAttributeVal($prod,$attributeName);			 ?>
            <span>
        </div>
    </div>
    <?php }
	}
	 ?>
     </div>
        </div> 
<?php
 $i++;
 if($ct == $i )
 {  
 	echo "</div>";	
 }
 
	  $type = $product->getValueId();
 } ?>   
    
</div>
<script type="text/javascript">
function launchDownload(softid)
{
	$('soft_detail_'+softid).show();
}
function hideDownload(softid)
{
	$('soft_detail_'+softid).show();
}
</script>



