<?php /********* Catalog Request form*******/ ?>
<?php $formData = Mage::getSingleton('core/session')->getCrFormData();  ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('catalogrequest')->__('Request Your Free Catalog!') ?></h1>
</div> 
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('catalogrequest_toptext')->toHtml() ?>
<form action="<?php echo Mage::helper('catalogrequest')->getCatalogRequestPostUrl(); ?>" id="catalogrequest-form" method="post"   name="catalogrequest-form">
      <div class="fieldset">
      <input  name="catalog_code"  type="hidden" value="<?php echo Mage::getStoreConfig('customer/catalogrequest/catalog_code');   ?>" />
      <p class="error_message">Please Note: Our catalog is shipped with every order. </p>
        <p class="description_text"><?php echo Mage::helper('catalogrequest')->__('Customer Shipping Information:') ?></p>
   		  <div class="catalogrequest-from">
          <ul>
	   		  <li>
	                <div class="field">
	                    <label for="name" ><?php echo Mage::helper('catalogrequest')->__('First Name:') ?></label>
	                    <div class="input-box">
	
	                      <input class="input-text validate-no-html-tags" name="firstname" id="firstname"  type="text" value="<?php echo  ($formData['firstname']?$formData['firstname']:'')  ?>" />
	                    </div>
	                </div>
	        </li>
	        <li> 
	         <div class="field">
	        		<label for="lastname"><?php echo Mage::helper('catalogrequest')->__('Last Name:') ?><span class="required">*</span></label>
		         	<div class="input-box">
			        	<input class="input-text validate-no-html-tags required-entry " name="lastname" id="lastname"  type="text" value="<?php echo  ($formData['lastname']?$formData['lastname']:'')  ?>" />
			        </div>   
		        </div>   
		     </li>
		     <li>
         		<div  class="field">
        			<label for="schoolname"><?php echo Mage::helper('catalogrequest')->__('School Name:') ?> </label>
		        	<div class="input-box">
				        <input class="input-text validate-no-html-tags" name="schoolname" id="schoolname"  type="text" value="<?php echo  ($formData['schoolname']?$formData['schoolname']:'')  ?>" />
			        </div>   
      		  </div>   
		     </li>
		     <li>
		        <div class="field">
		        <label for="mailing_address"><?php echo Mage::helper('catalogrequest')->__('Mailing Address:') ?><span class="required">*</span></label>
		       <div class="input-box"> <input class="input-text validate-no-html-tags required-entry validate-noemail " name="mailing_address" id="mailing_address"  type="text" value="<?php echo  ($formData['mailing_address']?$formData['mailing_address']:'')  ?>" /></div>
		        </div> 
		     </li>
		     <li>
				<div class="field">
			        <label for="appt_unit"><?php echo Mage::helper('catalogrequest')->__('Apartment/Unit:') ?> </label>
			      <div class="input-box">  <input class=" input-text validate-no-html-tags validate-noemail" name="appt_unit" id="appt_unit"  type="text" value="<?php echo  ($formData['appt_unit']?$formData['appt_unit']:'')  ?>" /></div>
			     </div> 
		     </li>
		     <li>
			    <div class="field">
			        <label for="city"><?php echo Mage::helper('catalogrequest')->__('City:') ?><span class="required">*</span></label>
			       <div class="input-box"> <input class="input-text validate-no-html-tags required-entry " name="city" id="city"  type="text" value="<?php echo  ($formData['city']?$formData['city']:'')  ?>" /></div>
		        </div>   
		     </li>
		    
		     <li>
 				<div class="field">
			        <label for="country"><?php echo Mage::helper('catalogrequest')->__('Country:') ?><span class="required">*</span></label>
			      	 <div class="input-box">
                 	 <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect();?>
           			</div>
		        </div>
		        
		     </li> 
		      <li>
		        <div class="field">
			        <label for="region1"><?php echo Mage::helper('catalogrequest')->__('State:') ?> <span class="required">*</span></label>
			       <div class="input-box">  <select class="browser-default" id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select required-entry" style="display:none;"><option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select> 
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $formData['region_id'] ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo ($formData['region']?$this->escapeHtml($formData['region']):'') ?>"   title="<?php echo $this->__('State/Province') ?>" class="input-text validate-no-html-tags required-entry" /> </div>
		        </div> 
		     </li>
		     <li>
				<div class="field">
			        <label for="zipcode1"><?php echo Mage::helper('catalogrequest')->__('Zipcode:') ?><span class="required">*</span></label>
			       <div class="input-box"><input name="zipcode" class="input-text validate-no-html-tags validate-zip-international "   id="zipcode"  type="text" value="<?php echo  ($formData['zipcode']?$formData['zipcode']:'')  ?>" /></div>
		        </div>
		     </li>
		       <li>
		        <div class="field">
		        <label for="email"><?php echo Mage::helper('catalogrequest')->__('Email:') ?><span class="required">*</span></label>
		        <div class="input-box"><input name="email" type="text" id="email"  class="validate-email required-entry  input-text" value="<?php echo  ($formData['email']?$formData['email']:'')  ?>" /></div>
		        </div> 
		     </li>
		     <li>
		       <div class="field">
		      	  <label for="phone"><?php echo Mage::helper('catalogrequest')->__('Telephone:') ?></label>
		     	   <div class="input-box"><input name="phone" class="input-text validate-no-html-tags " id="phone"  type="text" value="<?php echo  ($formData['phone']?$formData['phone']:'')  ?>" /></div>
		        </div>
		        
		     </li>
		     <li>
		        <div class="field">
		         <label> <input type="checkbox" name="sign_up"  class="checkbox" <?php if(isset($formData['sign_up']) && ($formData['sign_up'] =='1')): ?> checked="checked"<?php elseif (isset($formData['sign_up']) && ($formData['sign_up'] == '')):?>"" <?php else:?> checked="checked"<?php endif; ?> id="sign_up" value="1"/><span class="detail_text">Sign up for our E-Newsletter</span></label>
		      	 <div class="input-box"> </div>
		        </div>
        
		     </li>
		     <li>
		      <div class="field">
		        <label for="best_describe"  ><?php echo Mage::helper('catalogrequest')->__('Which best describes you?') ?><span class="required">*</span></label>
		      
		        <div class="input-box">
                <select onchange="if (this.options[this.selectedIndex].value == 'Parent') { this.form.cat_code.value='p'; } else if (this.options[this.selectedIndex].value == 'Home Educator') { this.form.cat_code.value='h'; } " class="input-text required-entry" name="market" size="1">
               		<option value="">-- Please Select --</option>
               		<?php $arrMarket = $this->helper('catalogrequest')->getAllMarket();?>
			        <?php foreach($arrMarket as $key => $value): ?>
			            <option value="<?php echo $key ?>" <?php echo (($formData['market'] == $key)?'selected="selected"':'')?>><?php echo $value ?></option>
			        <?php endforeach; ?> 
		         </select></div>
		        </div>
		        
		     </li>
			  <input type="hidden" name="bsest_sales_news" value="2405405"/>
		     <li>
		      <div class="field">
		        <label for="subject"><?php echo Mage::helper('catalogrequest')->__('What subjects are you teaching?') ?></label>
		       	 <div class="input-box">	<select  class="input-text" name="subject" size="1">
			        <?php $arrSubjects = $this->helper('catalogrequest')->getAllSubjects();?>
			        <option value="">-- Please Select --</option>
			        <?php foreach($arrSubjects as $key => $value): ?>
			            <option value="<?php echo $key ?>" <?php echo (($formData['subject'] == $key)?'selected="selected"':'')?>><?php echo $value ?></option>
			        <?php endforeach; ?> 
		            </select>	</div>
		        </div> 
		     </li>
		     <li>
	           <div class="field">
		        <label for="hear_about"><?php echo Mage::helper('catalogrequest')->__('How did you hear about us?') ?></label>
		      <div class="input-box">   <select class="input-text" name="hear_about" size="1">
		           <?php $arrHearAbout = $this->helper('catalogrequest')->getAllHearAbout();?>
			        <option value="">-- Please Select --</option>
			        <?php foreach($arrHearAbout as $key => $value): ?>
			            <option value="<?php echo $key ?>" <?php echo (($formData['hear_about'] == $key)?'selected="selected"':'')?>><?php echo $value ?></option>
			        <?php endforeach; ?> 
		            </select></div>
		           </div> 
		        
			     </li>
			     
                 <li>
                 <label>&nbsp;</label>
			     	<div class="input-box">
						<span class="required">* (required)</span><br />
			     		<p style="font-size: 0.9em;">We respect your privacy. E-mail addresses are not released to third parties.</p>
                        </div>
			     	
			     </li>
                 
				 <li>
			    <div class="field">
			        <label for="Captch">&nbsp;</label>
					
<?php //echo $this->getChildHtml('form.additional.info'); ?> 
<?php echo $this->getLayout()->createBlock('studioforty9_recaptcha/explicit')->setTemplate('studioforty9/recaptcha/explicit.phtml')->tohtml(); ?>
                           
                     
		        </div>  		        
		     </li>
				</ul>
                
            
                
                </div>
                
                   <div class="button-set-box">        
         <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('catalogrequest')->__('Submit') ?>" class="button-form"><?php echo Mage::helper('catalogrequest')->__('Submit') ?></button>
    </div>   
		 </div>
		 
         
         

  
</form>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('catalogrequest_rightbox')->toHtml() ?>


<script type="text/javascript">
//<![CDATA[
    var catalogrequestForm = new VarienForm('catalogrequest-form', false); 
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zipcode'); 
//]]>
</script>
