<div class="homepage_shopbysearch1">
<h3><img src="<?php echo $this->getSkinUrl('images/search-heading-home.jpg')?>" alt="" /></h3>
<!--<label><input name="search" type="text" value="SKU, Title or ISBN , DEMo" /></label>
<label><img src="<?php echo $this->getSkinUrl('images/shopneed-go-btn.png')?>" alt="" /></label>-->


<form action="<?php echo $this->getUrl('catalogsearch/advanced/result'); ?>" method="get" id="form-validate">
<?php $shop_need = array('isbn') ?>

  <?php foreach ($this->getSearchableAttributes() as $_attribute): ?>
        <?php $_code = $_attribute->getAttributeCode() ?>
        <?php  if(in_array($_code,$shop_need)) { ?>
<label>
		<?php switch($this->getAttributeInputType($_attribute)):
   		case 'select': ?>
                    <?php echo $this->getAttributeSelectElement($_attribute) ?>
                    <?php break;
        default: ?>
       
                <input name="<?php echo $_code ?>" id="<?php echo $_code ?>" value="SKU, Title or ISBN" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>"  class="input-text <?php echo $this->getAttributeValidationClass($_attribute) ?>" type="text" />
               
            <?php endswitch; ?>
            
<!--<select name="Select Grade">
  <option value="Select Grade">Select Grade</option>
</select>-->
</label>
  <?php } ?>
  <?php endforeach; ?>


    <script type="text/javascript">decorateList('advanced-search-list')</script>
<div style="display:none;" class="validation-advice">You have to specify at least one search term.</div>
<label><button class="form-button" type="submit"><span><?php echo $this->__('Go') ?></span></button><label>
  <!-- <label><img src="<?php echo $this->getSkinUrl('images/shopneed-go-btn.png')?>" alt="" /></label>-->
</form>
</div>