<?php
/**
 *
 * @category    Pisc
 * @package     Pisc_Downloadplus
 * @copyright   Copyright (c) 2009 PILLWAX Industrial Solutions Consulting
 * @license		Commercial Unlimited License (https://technology.pillwax.com/license)
 */

/**
 * Latest Updates on Downloads Dashboard Block
 *
 * @category    Pisc
 * @package     Pisc_Downloadplus
 * @author		Software Group @ PILLWAX Industrial Solutions Consulting (technology.license@pillwax.com)
 * @version		0.1.0
 */

/*
 * Available data of collection items (as Array):
 * 'title' => Title of Download
 * 'total' => Total of tracked downloads
 * 'product' => Product Model this download is related to
 */
?>

<?php
/*
 * Get recent updated files, limit to 5 max.
 * To get all, ommit limit.
 */
$_downloads = $this->getTopDownloads(5);
?>

<?php if(count($_downloads) > 0): ?>

<div class="box base-mini">
    <div class="head">
        <h4 class="title"><?php echo $this->__('Top Downloads') ?></h4>
    </div>
    <div class="content">

<?php $_updatesSize = count($_downloads) ?>
    <?php $i=0; foreach ($_downloads as $_download): ?>
        <?php if($i++%3==0): ?>
        <ol class="grid-row">
        <?php endif; ?>
            <li class="item">
            	<?php echo ($i);?>.&nbsp;
				<a href="<?php echo $_download['product']->getProductUrl(); ?>"><?php echo $_download['product']->getName(); ?></a><br />
                <?php echo $_download['title']; ?><br />
                (<?php echo $_download['total']; ?>)
            </li>
        <?php if($i%3==0 || $i==$_updatesSize): ?>
        </ol>
        <?php endif; ?>
    <?php endforeach ?>

	</div>
</div>
<?php endif; ?>
