<style type="text/css">
.donate_div{
	width:156px;
	float:left; padding-right:0px;
	padding-bottom:30px; text-align:left;
}
.donate_main_div
{
color:#cc0001; 
padding:15px 0 0 0; 
font-size:25px; 
font-weight:bold;  
}
</style>
<div class="donate_main_div">
<?php $products = $this->getAllDonateProducts();?>
<?php	if(sizeof($products)>0):?>
	<?php foreach ($products as $_product):?>
	<div class="donate_div" align="center"> 
		<a href="<?php echo $_product->getProductUrl()?>" title="<?php echo $this->htmlescape($_product->getName());?>">
		<img src="<?php echo Mage::helper('catalog/image')->init($_product, 'small_image')->resize(124,158); ?>"  alt="<?php echo $this->htmlescape($_product->getName());?>" />
		</a>
	</div>
	<?php endforeach;?>
<?php endif;?>

</div>