<?php /********* Catalog Request form*******/ ?>
<?php $formData = Mage::getSingleton('core/session')->getDrFormData();  ?>

<div class="page-title">
    <h1><?php echo Mage::helper('dealerskit')->__('Reseller Information') ?></h1>
</div> 
<?php if(isset($formData['success'])):?>
<div style="display:none;" id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('dealerskit_topbox')->toHtml();

Mage::getSingleton('core/session')->unsDrFormData(''); ?>
<?php else:?>
<form action="<?php echo Mage::helper('dealerskit')->getCatalogRequestPostUrl(); ?>" id="dealerskit-form" method="post"   name="dealerskit-form">
      <div class="fieldset" style="float:left;">  
        <p class="description_text"><strong><?php echo Mage::helper('dealerskit')->__('Request a Dealer Information Packet') ?></strong></p>
   		  <div class="catalogrequest-from">
          <ul>
	   		  <li>
	                <div class="field">
	                    <label for="company" ><?php echo Mage::helper('dealerskit')->__('Company Name:') ?><span class="required">*</span></label>
	                    <div class="input-box">
	
	                      <input class="input-text  validate-no-html-tags required-entry " name="company" id="company"  type="text" value="<?php echo  ($formData['company']?$formData['company']:'')  ?>" />
	                    </div>
	                </div>
	        </li>
	       
		     <li>
         		<div  class="field">
        			<label for="attention"><?php echo Mage::helper('dealerskit')->__('Attention:') ?> <span class="required">*</span></label>
		        	<div class="input-box">
				        <input class="input-text  validate-no-html-tags required-entry " name="attention" id="attention"  type="text" value="<?php echo  ($formData['attention']?$formData['attention']:'')  ?>" />
			        </div>   
      		  </div>   
		     </li>
		     <li>
		        <div class="field">
		        <label for="address1"><?php echo Mage::helper('dealerskit')->__('Address1:') ?><span class="required">*</span></label>
		       <div class="input-box"> <input class="input-text validate-no-html-tags required-entry " name="address1" id="address1"  type="text" value="<?php echo  ($formData['address1']?$formData['address1']:'')  ?>" /></div>
		        </div> 
		     </li>
		     <li>
				<div class="field">
			        <label for="address2"><?php echo Mage::helper('dealerskit')->__('Address2:') ?> </label>
			      <div class="input-box">  <input class=" input-text validate-no-html-tags" name="address2" id="address2"  type="text" value="<?php echo  ($formData['address2']?$formData['address2']:'')  ?>" /></div>
			     </div> 
		     </li>
		     <li>
			    <div class="field">
			        <label for="city"><?php echo Mage::helper('dealerskit')->__('City:') ?><span class="required">*</span></label>
			       <div class="input-box"> <input class="input-text validate-no-html-tags required-entry " name="city" id="city"  type="text" value="<?php echo  ($formData['city']?$formData['city']:'')  ?>" /></div>
		        </div>   
		     </li>
		 
		     <li>
 				<div class="field">
			        <label for="country"><?php echo Mage::helper('dealerskit')->__('Country:') ?><span class="required">*</span></label>
			       <div class="input-box">
			       	<?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect();?> 
                   </div> 
		        </div> 
		     </li>
	         <li>
		        <div class="field"> 
			        <label for="region"><?php echo Mage::helper('dealerskit')->__('State:') ?> <span class="required">*</span></label>
			       <div class="input-box">  <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select required-entry" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select> 
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $formData['region_id'] ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo ($formData['region']?$this->escapeHtml($formData['region']):'') ?>"   title="<?php echo $this->__('State/Province') ?>" class="input-text validate-no-html-tags required-entry" /> </div>
		        </div> 
		     </li> 
	        <li>
				<div class="field">
			        <label for="zipcode"><?php echo Mage::helper('dealerskit')->__('Zip/Postal Code:') ?><span class="required">*</span></label>
			       <div class="input-box"><input name="zipcode" class="input-text validate-no-html-tags validate-zip-international"   id="zipcode"  type="text" value="<?php echo  ($formData['zipcode']?$formData['zipcode']:'')  ?>" /></div>
		        </div>
		     </li> 
		     <li>
		       <div class="field">
		      	  <label for="phone"><?php echo Mage::helper('dealerskit')->__('Telephone:') ?><span class="required">*</span></label>
		     	   <div class="input-box"><input name="phone" class="input-text validate-no-html-tags  required-entry" id="phone"  type="text" value="<?php echo  ($formData['phone']?$formData['phone']:'')  ?>" /></div>
		        </div>
		        
		     </li>
		       <li>
		        <div class="field">
		        <label for="email"><?php echo Mage::helper('dealerskit')->__('Email:') ?><span class="required">*</span></label>
		        <div class="input-box"><input name="email" type="text" id="email"  class="validate-email required-entry  input-text" value="<?php echo  ($formData['email']?$formData['email']:'')  ?>" /></div>
		        </div> 
		     </li>
			     
                 <li>
                 <label>&nbsp;</label>
			     	<div class="input-box">
						<span class="required">* (required)</span><br />
			     		<p style="font-size: 0.9em;">We respect your privacy. E-mail addresses are not released to third parties.</p>
                        </div>
			     	
			     </li>
                 
				 <?php echo $this->getChildHtml('form.additional.info'); ?>
				</ul>
                
            
                
                </div>
                
                   <div class="button-set-box">        
         <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('dealerskit')->__('Submit') ?>" class="button-form"><?php echo Mage::helper('dealerskit')->__('Submit') ?></button>
    </div>   
		 </div>
		 
         
         

  
</form>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('dealerskit_rightbox')->toHtml() ?>


<script type="text/javascript">
//<![CDATA[
    var dealerskitForm = new VarienForm('dealerskit-form', false); 
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zipcode'); 
//]]>
</script>
<?php endif;?>