<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Relatedproducts
 * @version    1.4.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Relatedproducts
 * @copyright  Copyright (c) 2008-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @var $this AW_Relatedproducts_Block_Relatedproducts
 */
?>
<?php if($this->getEnabled() && count($this->getRelatedProductsCollection())): ?>
<script src="<?php echo $this->getSkinUrl('js/jquery.bxslider.min.js'); ?>"></script>
<link href="<?php echo $this->getSkinUrl('css/jquery.bxslider.css'); ?>" rel="stylesheet" />
<div class="aw-box aw-mini-related-items block1 nwslide">
<div class="aw-content-box1">
    <div class="head">
        <h4><?php echo $this->__('Customers Who Bought This Also Bought') ?></h4>
    </div>
    <div class="aw-content" <?php if (Mage::helper('relatedproducts')->checkVersion('1.4.1.0')) { echo "id=\"after1400\""; }?>>
       <?php /* <p><strong><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllAwRelated(this);return false;"><?php echo $this->__('select all') ?></a></strong></p>      */ ?>   
        <ol class="alsoboughtthis">
        <?php $ij = 0;$total = count($this->getRelatedProductsCollection()); foreach($this->getRelatedProductsCollection() as $_item): $ij++;?>
        <li class="<?php if($_item->isComposite() || !$_item->isSaleable()): ?> super-products <?php endif; ?><?php if($ij == $total):?> last <?php endif;?> ">
            <div class="product-images">
            <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
               
            <?php /* <span class="checkbox-container">
                <?php if (!$_item->getRequiredOptions()): ?>
                    <input type="checkbox" class="aw-related-checkbox left" id="aw-related-checkbox<?php echo $_item->getId() ?>" name="aw_related_products[]" value="<?php echo $_item->getId() ?>" />
                <?php endif; ?>
                </span>
                    */ ?>
            
            <?php else: ?>
                <span class="checkbox-container">&nbsp;</span>
            <?php endif; ?>
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(130,140) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="130" height="140" /></a>
            </div>
            <div class="product-details">
                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    <?php if(is_null($_item->isSaleable() && $_item->getAvailableText())){?>
                    	  <div class="available_text"><font color="#0033CC"><?php echo  $_item->getAvailableText()?></font></div>
                    <?php } else {?><?php echo $this->getPriceHtml($_item, true); ?>
                
                    <?php }?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="aw-link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
            </div>
        </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
</div>   

<script type="text/javascript">
<!--
$$('.aw-related-checkbox').each(function(elem){
    Event.observe(elem, 'click', addAwRelatedToProduct)
});

var relatedAwProductsCheckFlag = false;
function selectAllAwRelated(txt){
    if (relatedAwProductsCheckFlag == false) {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = true;
        });
        relatedAwProductsCheckFlag = true;
        txt.innerHTML="<?php echo $this->__('unselect all') ?>";
    } else {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = false;
        });
        relatedAwProductsCheckFlag = false;
        txt.innerHTML="<?php echo $this->__('select all') ?>";
    }
    addAwRelatedToProduct();
}

function addAwRelatedToProduct(){
    var checkboxes = $$('.aw-related-checkbox');
    var values = [];
    for(var i=0;i<checkboxes.length;i++){
        if(checkboxes[i].checked) values.push(checkboxes[i].value);
    }
    
    if($('related-products-field')){
        $('related-products-field').value = values.join(',');
    }
    
}
//-->

jQuery(document).ready(function(){

    jQuery('.alsoboughtthis').bxSlider({
        slideWidth: 174,
		pager: false,
        maxSlides: 4,
        slideMargin: 10
    });
});
</script>


<?php endif ?>
